### ISSUE TITLE
[REQUEST] Predict what pattern we are/aren't in.

### ISSUE THREAD

**Issue by AustinYQM** [elxris/Turnip-Calculator#1]
If I am understanding correctly it should be possible to predict what pattern you are in kind of quickly. For example, I bought turnips for 90 and my Monday numbers were 67 and 61 for the morning and afternoon respectfully. This tells me that I can't be in a decreasing pattern as the drop from 90->67 is just too sharp.

**Comment by Lyrratic** [comment]
Are you thinking of functionality along these lines? https://kurtboyer.com/stalkmarket/#turnips

**Comment by AustinYQM** [comment]
Yeah. A list of still possible patterns under the graph would be pretty awesome. I know its the first thing I check when Monday sucks.

**Comment by MrAspas** [comment]
In this website explain a equation that helps knowing which pattern you might be in just by the turnips buying price and the first selling price of the week, which would be cool to see implemented to predict what pattern  we are in https://forswornseparatist.tumblr.com/post/614554762350903296/a-guide-to-animal-crossing-stonks

**Comment by elxris** [comment]
This pattern recognition is intended for very involved people in turnip patterns.
I think if we add this pattern list to the tool we should explain what each pattern means.
I think it complicates it a bit for inexperienced or casual gamers.

**Comment by darknerd42** [comment]
As a stop gap to full pattern recognition, it'd be neat to be able to display the graph with the data from just a selected pattern type so you could see how your prices fit into those patterns.

**Comment by thesnwmn** [comment]
> This pattern recognition is intended for very involved people in turnip patterns.
> I think if we add this pattern list to the tool we should explain what each pattern means.
> I think it complicates it a bit for inexperienced or casual gamers.

I see where your coming from but I think the following is a good example of a confusing graph without pattern data. The reality here is that it could be decreasing, small spike or large spike. A list of the patterns this could be might help people understand clearly that they could already be at their maximum.

![DB26DD56-C4FA-4CE6-A4DD-88E5F378BA2D](https://user-images.githubusercontent.com/26804092/79303319-83fa0580-7ee6-11ea-89df-bb8c8db7a110.png)

**Comment by elxris** [comment]
I have released 1.9.1 and now we have something like this. 

![image](https://user-images.githubusercontent.com/1855014/80296318-7e4ebc00-873f-11ea-875e-a1c91fd10b22.png)

Please look at it and come back with feedback. I'm excited this will help a lot of us.

**Comment by DaVince** [comment]
I came here wondering about the pricing patterns as well. I don't actually know by looking at the graph which part of it indicates what kind of pattern I'm in. Is it the yellow line? As it is, I still get confused by the lower and upper limits of the graph.

My thought for improving on this is to have a small paragraph of text below the graph indicating what the calculator thinks the pattern may be and what it means.

**Comment by elxris** [comment]
The graph now has a table with a lot of information. I will close this for now, but if you feel like it's more to add to it, please open another issue. Thank you a lot to all the people that participated in this issue.
