### ISSUE TITLE
[Request] Guaranteed Minimum Price

### ISSUE THREAD

**Issue by capoferro** [elxris/Turnip-Calculator#10]
Example data:

Purchase price: 91
Mon AM: 47
Mon PM: 43
Tues AM: 39

The chart seems to indicate that there's a chance that the price will never break 100, but that's not actually true. Every pattern actually hits 126 minimum at some point during the week, even if all patterns combined have a chance of being below 100 every day. 

I'm not a dataviz expert, so I'm not sure what options there are to improve this, but somehow indicating that all patterns will at least hit a certain minimum is useful information that the chart obscures due to how the patterns can be offset by a day from eachother throughout the week.

Maybe we can just add a note at the bottom of the table indicating the smallest possible peak across all patterns, so you can tell whether the value you're currently seeing is lower than peak on the worst available pattern.

**Comment by elxris** [comment]
![image](https://user-images.githubusercontent.com/1855014/78689371-e1c19880-78bb-11ea-9d4b-cf892e9518f1.png)
This is the graph I'm seeing with your data.

Correct me if I'm wrong but I'm not seen what are you describing.

**Comment by capoferro** [comment]
Yeah, so, if you look, it seems to suggest that you may not see anything higher than ~81, but that's not actually true. All patterns hit at least 126 at the very minimum, it's just they hit that number on different days, which means the minimum every day is lower than that.

**Comment by elxris** [comment]
Oh, you mean "Buy price" dotted line? That's just your 91 value buy price.

**Comment by capoferro** [comment]
Maybe I'm just misunderstanding and my challenges are unique to me. I'm looking at the lower dark green section. It never goes over the buy price, even though every pattern that the prices match so far do exceed the buy price at some point.

**Comment by elxris** [comment]
How do you know that 126 is your minimum and not ~80 like the graph suggests?

**Comment by nanoNago** [comment]
for the buy price and prices given (assuming it's not the first buy week), the remainder of that week is exactly:

```
BumpModel Model Analyses:
  5 model(s) remaining
  base price: 91

  5 possible peak times:
  - peak time: TimePeriod.Thursday_AM
      base price: 91
  - peak time: TimePeriod.Thursday_PM
      base price: 91
  - peak time: TimePeriod.Friday_AM
      base price: 91
  - peak time: TimePeriod.Friday_PM
      base price: 91
  - peak time: TimePeriod.Saturday_AM
      base price: 91

  Summary: 
    Time          Price                   Likely                  Odds  
    Monday_AM:    47;                     47;                     (100.00%)
    Monday_PM:    43;                     43;                     (100.00%)
    Tuesday_AM:   39;                     39;                     (100.00%)
    Tuesday_PM:   {[34, 37], [82, 128]};  [34, 37];               (25.40%)
    Wednesday_AM: {[29, 34], [82, 128]};  [29, 34];               (16.07%)
    Wednesday_PM: {[25, 31], [82, 181]};  [127, 128];             (3.68%)
    Thursday_AM:  {[20, 29], [82, 182]};  128;                    (1.87%)
    Thursday_PM:  [82, 182];              128;                    (1.93%)
    Friday_AM:    [37, 182];              128;                    (1.55%)
    Friday_PM:    {[32, 82], [127, 182]}; [128, 181];             (62.31%)
    Saturday_AM:  {[28, 82], [127, 182]}; [37, 77];               (48.24%)
    Saturday_PM:  {[23, 82], [127, 181]}; [37, 74];               (60.32%)
```

for any *individual* possibility, you can still experience a low price on any *given* day, so the low numbers in the chart are still possible -- just not all simultaneously, if that makes sense. This would be a composite of five possible graphs, each with a different peak for your modest bump.

This graph looks right to me.

**Comment by capoferro** [comment]
![image](https://user-images.githubusercontent.com/57349/78697381-b72d0b00-78ce-11ea-92b8-12ba646f757f.png)


What I'm trying to say is that all of the possible patterns will at least hit 126 at some point. Is this table incorrect? (https://turnipprophet.io/index.html)

**Comment by nanoNago** [comment]
Here is my exact math for the five possible patterns you may be on: https://gist.github.com/nanoNago/9b1dfdb63c7df3d208ceb0d890cdcdef

(Bump pattern (no. 3) with five different peak times.)

You're right, each *individual* model will hit at least 127 (I think 126 is too low, actually...?)
but we don't know when your *exact* peak will be, so we can't draw a better minimum -- that's why the maximum in the graph looks like a big pleateau instead of a peak: it could be at just about any time.

**Comment by capoferro** [comment]
Right, so that's what I'm getting at. I wonder if there's a way to say "at some point, you'll get to at least 126 (or 127), so the value you currently have is guaranteed not to be what you will eventually get, regardless of what day it occurs on. The projected chart, because of the indeterminate day in this pattern, is too fuzzy to communicate that, I was thinking. It's not _wrong_, per se, but it's not useful.

**Comment by nanoNago** [comment]
ah, I see!

so you want a low water mark across all the remaining viable models. In this case, it'd be something like another dotted line at y=127.

**Comment by capoferro** [comment]
That might work, yeah. That sounds like a pretty straight forward solution.

**Comment by elxris** [comment]
Thank you for all your input!

I think I now see it! This is really useful.

Something like: "Dont sell line!"?

**Comment by capoferro** [comment]
At the risk of adding yet more complexity... perhaps it needs a confidence interval

**Comment by elxris** [comment]
Confidence is also hard to understand.

I would like to go with a “Week minimum” dotted line.

**Comment by elxris** [comment]
![image](https://user-images.githubusercontent.com/1855014/78731749-2a9e3f00-7906-11ea-84cb-9ba66df4a55d.png)
What do you think?

**Comment by mtaylor76** [comment]
It's a little unclear exactly what "Week min" means. Is it your minimum price throughout the week? (clearly not, since you have lower prices earlier in the graph.) 

I think it'd be better if the line were changed to a point if possible, and if label were changed to "Guaranteed Min" or something that conveys the idea of "your price will get *at least this high*" more clearly. You might also want to explain in the "Usage" section what that line means in more detail.

**Comment by elxris** [comment]
Thank you! That would be great!

**Comment by capoferro** [comment]
Thanks for doing this. <3

**Comment by elxris** [comment]
It is live!

**Comment by brikr** [comment]
Hi friends, sorry for necro
I read through this thread and I _think_ I understand what "Guaranteed Min" is now, but it's still a little confusing. I think the suggestion of making it a single point on the graph instead of the line would help greatly, and maybe there is still room for improvement on the label it's given (although I can't think of something better right now).

Ideally, someone wouldn't have to find this issue to learn what the data means 😅 

Just for my own clarification: We are currently half way through the week, and "Guaranteed Min" is 77. Does that mean that my price will be at least 77 at some point in the remainder of the week?

Cheers

**Comment by elxris** [comment]
Yeah, fix in it in a single point would be lot more confusing that already is. I think.

Because it’s not fixed to a point of the week. It’s a value for the current week.

And yes, 77 would be your lowest price, only if you are really, really salty.

**Comment by brikr** [comment]
Ah I see how a line might make sense then.

I'm not sure what you mean about 77 being my lowest price. I've already had prices lower than 77 this week. Here's my graph for reference:
![image](https://user-images.githubusercontent.com/10791216/78810300-6debc280-7985-11ea-9931-86f4f56aa6c6.png)

If "Guaranteed Min" is referring to a price you'll see in the future, then I think the line is fine (although maybe the line could start at the current day to show that it's not referring to the past), and it might be useful to update the information text about it below to something like
```
- The Guaranteed Min value means that you will see at least this price at some point during the remainder of the week.
```

**Comment by elxris** [comment]
It will not decrease by any means with new data being entered. It could go high, as more patterns are filtered.

But also, is not for the future, or remainder of the week. You may have reached that guaranteed price already. Any price point more or equal to the guaranteed may be the only one. But for each week you will always hit that price.

**Comment by brikr** [comment]
Thank you, this makes a lot more sense!
My final suggestion would be to name it "Guaranteed Price" instead of "Guaranteed Min". I think the "minimum" part of it is what is causing confusion for me at least.

**Comment by elxris** [comment]
Totally right! I think it makes more sense.
