### ISSUE TITLE
Microsoft Edge gives slightly different results when compared to Safari and Firefox

### ISSUE THREAD

**Issue by Rueshann** [elxris/Turnip-Calculator#103]
Microsoft Edge is giving slightly different results when compared to Safari and Firefox. The attached screen shots show the same Buy and Monday AM prices, but the Wednesday AM approximation is slight off when compared to the other 2 browsers. The Edge screenshot is the one on the bottom. 

<img width="469" alt="Safari Screen Shot 2020-04-27 at 8 37 11 AM" src="https://user-images.githubusercontent.com/32078013/80373212-b995db80-8862-11ea-80b4-d8548022d0f6.png">
<img width="456" alt="Firefox Screen Shot 2020-04-27 at 8 36 40 AM" src="https://user-images.githubusercontent.com/32078013/80373214-ba2e7200-8862-11ea-85d2-08ec78dadf0f.png">
<img width="509" alt="Edge Screen Shot 2020-04-27 at 8 36 26 AM" src="https://user-images.githubusercontent.com/32078013/80373215-ba2e7200-8862-11ea-8f29-e0baacd2c5b8.png">

**Comment by elxris** [comment]
It’s a version mismatch issue.
