### ISSUE TITLE
[FEATURE] Adding a table containing tooltips informations

### ISSUE THREAD

**Issue by MarkVador49** [elxris/Turnip-Calculator#106]
More a suggestion than a bug.

I was wondering if it was possible for you (and especially if it's considered "practical" by the community), to add a table under the graph, containing all the tooltip information. This would allow us to have all the information at a glance.
See the capture below.

Apart from that, excellent work, it's an extremely handy tool, thanks and congratulations to everyone who worked on the project.

![tableau acturnip](https://user-images.githubusercontent.com/64464311/80466010-38ab1280-893c-11ea-9b47-30981fb64291.png)

**Comment by elxris** [comment]
I will close this as it's live on the website right now. If you feel like there's more to add to it please open a new ticket. Thank you a lot for opening this ticket.
https://github.com/elxris/Turnip-Calculator/issues/115#issuecomment-631852759
