### ISSUE TITLE
[FEATURE] Release of Dataset

### ISSUE THREAD

**Issue by granthussey** [elxris/Turnip-Calculator#108]
**Is your feature request related to a problem? Please describe.**
A small problem - I find it hard to trust turnip websites that don't release their raw datasets for other data scientists to use to verify findings.

**Describe the solution you'd like**
Release of the raw datasets used to predict turnip prices

**Describe alternatives you've considered**
In the data science field, it is important to openly share data for researchers to replicate findings, so I believe that releasing the data is the best solution. However, at the very least, the individuals who created the predictive engine should publish online their methods and validation techniques. 

**Additional context**
I'm not saying anyone did something wrong, I'm just suggesting it would be best to release the data.

**Comment by elxris** [comment]
Related: #106
I will close this to continue the conversation in one place.
