### ISSUE TITLE
[BUG] The graph doesn't show when I put data in, put does show in the process of sharing it. Cannot see precision.

### ISSUE THREAD

**Issue by tootkoro** [elxris/Turnip-Calculator#112]
**Version of the tool**
It is at the bottom right corner. We only accept issues from >2.0.1

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by elxris** [comment]
It's probably a cache issue, could you please try to force refresh?
But I'm gonna close this as it's poorly filled.
