### ISSUE TITLE
[BUG] Different charts between browsers

### ISSUE THREAD

**Issue by UrbanSamurai** [elxris/Turnip-Calculator#113]
**Version of the tool**
v2.0.1-build.16

**Describe the bug**
Chart is not same in browser or on smartphone

**To Reproduce**
1. Go to chrome ( i have test with ie and firefox it's same )
2. put your data
3. check same on chrome on phone

**Expected behavior**
Same chart

**Screenshots**
![image](https://user-images.githubusercontent.com/64860442/81098666-fd937b00-8f09-11ea-934f-528deea15813.png)

![Screenshot_20200505_190423_com android chrome](https://user-images.githubusercontent.com/64860442/81098557-d2109080-8f09-11ea-8451-a51d41292f5d.jpg)
![Screenshot_20200505_190427_com android chrome](https://user-images.githubusercontent.com/64860442/81098562-d341bd80-8f09-11ea-9d4d-083fb9701815.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 1909
 - Browser: Chrome
 - Version: Version 81.0.4044.129

**Smartphone (please complete the following information):**
 - Device: Huawei P30 Pro
 - OS: EMUI 10.0.0.190
 - Browser chrome
 - Version : 81.0.40.44.117

**Additional context**

**Comment by elxris** [comment]
Do Desktop and Mobile versions of the website match?

**Comment by UrbanSamurai** [comment]
I check it and no it's not same versionBut what is the best correct version, seems 2.0.1 not realist for nowGuillaume GalloisLe 5 mai 2020 23:01, Christian Ceciliano <notifications@github.com> a écrit :
Do Desktop and Mobile versions of the website match?

**Comment by elxris** [comment]
Fixed some errors, I recently moved the core of the predictions to other technology to achieve best results. But I made a mistake in the algorithm.
v2.0.1-build.17 is the latest, please check it out and tell me if now looks good enough.

**Comment by UrbanSamurai** [comment]
Yes its not same than in build 16 but not at all of 1.9.1 I will check tomorrow to give you the best prediction build 😁Guillaume GalloisLe 6 mai 2020 00:11, Christian Ceciliano <notifications@github.com> a écrit :
Fixed some errors, I recently moved the core of the predictions to other technology to achieve best results. But I made a mistake in the algorithm.
v2.0.1-build.17 is the latest, please check it out and tell me if now looks good enough.

**Comment by elxris** [comment]
I was looking at previous bugs, and found #95 interesting.

Turns out I found the issue and fixed it. Maybe this will help as well.

Deployed: v2.0.1-build.18

**Comment by UrbanSamurai** [comment]
Thanks.

![image](https://user-images.githubusercontent.com/64860442/81205778-73135000-8fcb-11ea-9e15-94d066f19815.png)

so i have sell my turnips :) i bought at 104 and sell at 129. So good Job ! ( even i start only in trading (4800 turnips) )

version 1.9.1 was a little bit better cause the curve was growing in afternoon and not decrease.

Have a good day !

**Comment by elxris** [comment]
Thank you for the following up!
I think I can close the ticket now.
