### ISSUE TITLE
[BUG] Chart not appearing in Edge (Windows 10)

### ISSUE THREAD

**Issue by lmct1992** [elxris/Turnip-Calculator#114]
**Version of the tool**
v2.0.1 - build 18

**Describe the bug**

The graph does not load at all in Microsoft Edge despite working fine last week. I've tried several things such as disabled AdBlocker, clearing the Cache, turning my high contrast settings on and off in Windows but the chart si ply will not load.

I don't know if its just me or if anyone else has experienced this?

**Comment by elxris** [comment]
Which version of Edge are you using?
Just tested on 81.0.416 and worked fine.

**Comment by DragonEleven** [comment]
I have the same problem... was working fine until around Tuesday or Wednesday, at which point the graph just stopped showing up (just has the blank box where the graph should be), and nothing I've tried has fixed it.
I'm on Windows 10 version 1909, Edge version 44.18362.449.0.
I've checked my update history and the last Windows/Edge update I had was over a week before the problem started, so we can probably rule that out as being the cause.

**Comment by elxris** [comment]
Sorry, I don't have a way to test this version of Edge. Probably some error is displayed on the console?

**Comment by DragonEleven** [comment]
Sorted it... I hadn't realised that the version of Edge I was using had stopped auto-updating.
Had to manually install the newer version to get it up to date and now the graph is appearing again.

**Comment by KevinZjYang** [comment]
Using webview in UWP will not display the chart. v2.0.1-build.23
![image](https://user-images.githubusercontent.com/31529584/81959259-c0359880-9641-11ea-8e00-797aa976a970.png)

this is error.
![image](https://user-images.githubusercontent.com/31529584/81959099-8cf30980-9641-11ea-8c2d-0f92896f012a.png)
Many items are not expanded, hope it helps.

**Comment by elxris** [comment]
I am sorry, @KevinZjYang what is UWP?

**Comment by KevinZjYang** [comment]
@elxris  [Universal Windows Platform]( https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide)

**Comment by elxris** [comment]
Thank you for your response, however, I don't see the issue. I can't reproduce.

**Comment by KevinZjYang** [comment]
@elxris In v2.1.0-build.1, the chart returns to normal display.

**Comment by elxris** [comment]
Yes. Actually I found a bug around the fallback of WASM. If the platform fails to load the WASM core of calculations I will use fallback computation. (Pregenerated set of probabilities). It should work and be useful, but it generates less precise predictions. If you want to get better results I recommend using Firefox or Chrome. Chrome for Android also works well.

**Comment by elxris** [comment]
@lmct1992 if you still have this issue please file another issue. I think is now resolved.
