### ISSUE TITLE
[BUG] Input price labels do not automatically resize to multiline strings

### ISSUE THREAD

**Issue by Pkawa** [elxris/Turnip-Calculator#118]
**Version of the tool**
v2.0.1-build.23

**Describe the bug**
Localized string overlap on price input fields

**Steps to reproduce the behavior:**
1. Change language to Polish
1. Check localized strings over input fields

**Screenshots**
https://i.imgur.com/Om4ffqT.png 

**Desktop (please complete the following information):**
OS: Windows 10 64-bit
Browser Google Chrome
Version 81.0.4044.138

**Additional context**
Changing margin-top to 25px seems to fix the problem (https://i.imgur.com/oWtqM8X.png), some content wrapping to resize automatically (or grouping label and input field in some sort of column to remove the need for hardcoded margin - I don't know, I hate frontend 😄 ) would be better, probably.

**Comment by jhinton2015** [comment]
Hello, I suggest using a margin on the image itself so that it'll space out from the label about it. I was able to do this in my browser using: 
`.MuiInputAdornment-root {
    height: 0.01em;
    display: flex;
    max-height: 2em;
    align-items: center;
    white-space: nowrap;
    margin-top: inherit;
}`
where it inherits the top of the margin. I tried in multiple languages to make sure it auto resized

**Comment by elxris** [comment]
Thank you for reporting, this will be fixed soon.
