### ISSUE TITLE
[BUG] Incorrect graphs

### ISSUE THREAD

**Issue by Bramble39** [elxris/Turnip-Calculator#121]
**Version of the tool**
2.1.0-build.3

**Describe the bug**
Graph information seems to display incorrectly; the same data that correctly predicted a spike a few days ago now takes away any possibility of a spike despite it being pretty obviously wrong.

**To Reproduce**
Just compare to old screenshots I guess?

**Expected behavior**
The graph should have still predicted the spike because the data input was the exact same, and the spike did indeed exist.

**Screenshots**
This is the old graph which correctly displayed the spike.
![image](https://user-images.githubusercontent.com/65576035/82272050-8917fd80-9947-11ea-95c0-2a04c29aaf4a.png)

This is from today with the same data inputs.
![image](https://user-images.githubusercontent.com/65576035/82272094-a351db80-9947-11ea-8cdb-095a5fe8bdd9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 81.0.4044.138

**Comment by elxris** [comment]
Thank you a lot for this report. I did found a bug.
![image](https://user-images.githubusercontent.com/1855014/82395629-8a156180-9a11-11ea-89f8-5c994dc8cb1e.png)
The fix is live on 2.1.0-build.6.
I will close this issue but feel free to open another if you still see the bug.
