### ISSUE TITLE
[BUG] Display error 

### ISSUE THREAD

**Issue by otchiii** [elxris/Turnip-Calculator#122]
V2.1.0-build.4

Display error, the graph disappears.
1. Set buy price to 107
2. Set Mon AM to 127, Mon PM to 130
3. Set Tue AM to 154, Tue PM at 202
4. Scroll down to the graph 

There will be a zone where the new colours of the graph disappear from Tue AM to Wed AM

![IMG_1060](https://user-images.githubusercontent.com/65647481/82414820-e90dc180-9a77-11ea-905f-328ed57df1fd.png)

 - Device: iPad Pro (10.5 inch)
 - OS: iPad OS 13.4.1
 - Browser Safari
 - Version 13.1

**Comment by elxris** [comment]
This was fixed previously. Please update.
