### ISSUE TITLE
[BUG] Wrong Prediction

### ISSUE THREAD

**Issue by wedgietales** [elxris/Turnip-Calculator#123]
**Version of the tool**
v2.1.0-build.5

**Describe the bug**
Incorrect prediction

**To Reproduce**
Buy price: 110
Mon AM: 76
Mon PM: 70
Tue AM: 64
Tue PM: 119
Wed AM: 143

At this point the curve shows that my prices will increase again and remain high over the next 3 periods. But this wednesday afternoon my price dropped 82 Bells.

**Screenshots**
![image](https://user-images.githubusercontent.com/65672681/82469953-b6bd8d80-9a92-11ea-8f1c-19c84d4d7b67.png)

![image](https://user-images.githubusercontent.com/65672681/82469883-a0173680-9a92-11ea-89fc-05d1144c1541.png)

**Comment by elxris** [comment]
Oh, this is totally weird.
I tried to run the same numbers and it's giving me a different graph.

![image](https://user-images.githubusercontent.com/1855014/82566299-4faae200-9b41-11ea-8176-0345d3e0db46.png)

I need more details like Operative System with version, Browser with version.

Also, do you see this in v2.1.1-build.1?

**Comment by elxris** [comment]
Also, I did a fix (#121) that I released at v2.1.0-build.6, that's why I see a different graph that is correctly predicting your 86 bell price. But please confirm that you see a correct graph prediction with v2.1.1.

**Comment by wedgietales** [comment]
Today when I go to the site I am on v2.1.0-build.7, and I see the correct graph. I am not sure why I was on an old build yesterday. I am using Windows 10 and the current Google Chrome version 81.0.4044.138. I don't know how to switch to v2.1.1.

**Comment by elxris** [comment]
I enabled a "hard cache", just to make the site available on offline situations.
To update:
- Load ac-turnips.com, ensure that you have internet.
- Wait 15-30 seconds.
- Close the browser (all the windows and processes).
- Open the browser again and you should see the new site. :)

I will close the issue, I think it's solved. Thank you a lot for reporting this.
