### ISSUE TITLE
[BUG]Prediction Model erroneous

### ISSUE THREAD

**Issue by robertpb** [elxris/Turnip-Calculator#124]
**Version of the tool**
v2.1.1-build.7

**Describe the bug**
A set of input with empty entries in between that can only represent a decreasing model is predicted to have a possibility of small spike model.

**To Reproduce**
1. Go to https://ac-turnip.com/
2. Input the following set of prices:
Buy: 98
Mon AM: 84
Mon PM: 80
Tue AM: 76
Tue PM: 72
Wed AM/PM: Empty
Thu AM: Empty
Thu PM: 58
Others: Empty
2. See error

**Expected behavior**
This set of input should only belong to the decreasing model, since the small spike model must have 5 consecutive prices higher than 90% of the buy price, which is impossible in this set of input.

**Screenshots**
![image](https://user-images.githubusercontent.com/6861049/82744480-ba753c80-9d3e-11ea-916c-105723674792.png)
![image](https://user-images.githubusercontent.com/6861049/82744487-d4af1a80-9d3e-11ea-902d-a99259670252.png)
![image](https://user-images.githubusercontent.com/6861049/82744516-2fe10d00-9d3f-11ea-8074-4648bbb8091c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 v1909 Build 18363.836
 - Browser: Chrome
 - Version: 81.0.4044.138

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 13.3.1
 - Browser: Safari
 - Version: Stock

**Additional context**
https://turnipprophet.io?prices=98.84.80.76.72....58....
See the link above for what I believe to be a more accurate prediction for this set of input.

Edit: Wording; Uploaded screenshots instead of a link

**Comment by elxris** [comment]
Thank you a lot! I have released a fix. (2.1.1-build.9) This was a small piece of the algorithm that was overlooked by me. I think it's fixed now.

![image](https://user-images.githubusercontent.com/1855014/82849225-89227b00-9ebc-11ea-99ff-7feea0ac85e7.png)
