### ISSUE TITLE
[FEATURE] Update README.md with local development instructions

### ISSUE THREAD

**Issue by SHewitt95** [elxris/Turnip-Calculator#126]
What do we think about the README having a section detailing how to run this app locally? A process that may seem straightforward to some could be opaque for others. It'd be great if we could be accommodating to coders of all experiences/abilities who want to contribute to this project.

For example, I did the following commands:

```
git clone git@github.com:elxris/Turnip-Calculator.git
cd Turnip-Calculator
npm i
npm start
```

This was my best guess, based on my own experience and reading the `package.json`. However, I encountered this error:

```
'BROWSER' is not recognized as an internal or external command,
operable program or batch file.
```

Not quite sure what this error is about, but I ran `npx react-app-rewired start` to get around it and start the app.

So really, two questions:

1. How do we feel about updating the README.md?
2. What is that error?

**Comment by elxris** [comment]
What OS are you running?

**Comment by SHewitt95** [comment]
I am using Windows!
