### ISSUE TITLE
[BUG] Buy Price shows up as Monday AM price (iOS)

### ISSUE THREAD

**Issue by Rhaynaries** [elxris/Turnip-Calculator#140]
Using Apple iOS and Safari (v2.1.1-build.12) the buy price shows up under Monday AM. I tried deleting it to see what happened and then it shows up like there’s no value entered. 

![4E2FD5CD-D4B3-4DCC-9E74-0A33E513AD59](https://user-images.githubusercontent.com/66798529/84426577-1407b300-abe9-11ea-9595-55d18a594abb.jpeg)
![D1B7CF83-D44F-4AB7-BE65-7EB75E5AEB68](https://user-images.githubusercontent.com/66798529/84426584-166a0d00-abe9-11ea-9a97-3613ee714a91.png)

**Comment by elxris** [comment]
#130
It's already fixed, just update:

1. Load the site and ensure that you have internet.
2. Wait 15-30 seconds.
3. Close the browser (force quit safari).
4. Open the browser again and you should see the new site. :)
