### ISSUE TITLE
Doesn't predict when turnip buy price is above 100

### ISSUE THREAD

**Issue by beelzeboob** [elxris/Turnip-Calculator#142]
**Version of the tool**
2.1.2

**Describe the bug**
Doesn't predict at all when buy price is over 100

**To Reproduce**
Calculate starting with any buy price over 100
Put in daily selling price

**Expected behavior**
Prediction does not even remotely match, even after all data from weds onwards put in 
Or just a flat line 

**Screenshots**
![Screenshot_20200623-161212](https://user-images.githubusercontent.com/67330291/85421543-727b4c80-b56c-11ea-8dee-e7fc0006f07b.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Nokia 8
 - OS: ?
 - Browser: chrome
 - Version: ?

**Additional context**
Works absolutely fine otherwise. Only has issues when buy price is over 100
Has happened 3 separate times and all times were when above 100

**Comment by elxris** [comment]
Hi @beelzeboob, I have reviewed your problem but I think there is no problem at all. As you see in the table chart you will see that you’re in random/fluctuating pattern. We can’t predict much better than that.

I don’t think it’s related to the price being more than 100. I can use your buy prices without specifying the buy price and will give me the same pattern. But please pay attention to changes of predicted pattern. If changes from 100% fluctuating to 100% high spike, then it’s safe to assume some kind of bug.

Please be sure to post your buy price along your other prices just to replicate your case if it keeps happening.
