### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LadyRyu** [elxris/Turnip-Calculator#149]
**Version of the tool**
It is at the bottom right corner. We only accept issues from >2.1.2-build.20

**Describe the bug**
On my iphone 8, standard safari browser, i get a very flat curve 93-99-88-100. 
if I add the same numbers on my laptop, firefox browser 93-99-88-100 i get a possible high peak on wednesday morning. 
It is the same version according to numbers (v.2.1.2-build.20)

**To Reproduce**

**screenshots**

![57299D00-F196-4512-BD13-4B39C1B02312](https://user-images.githubusercontent.com/67628107/87395259-643faf80-c5b1-11ea-9421-9a5b6e75c215.png)
![image](https://user-images.githubusercontent.com/67628107/87395356-83d6d800-c5b1-11ea-9b12-3ddcd25515c2.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari]firefox

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone8
 - OS: [e.g. iOS8.1] iOS 13.5.1
 - Browser [e.g. stock browser, safari] Safari 
 - Version [e.g. 22] newest

**Additional context**

**Comment by elxris** [comment]
Thank you for reporting this.

Just to let you know. There are two sites that host this tool. Nooknet which is managed by Nooknet and ac-turnip.com which is managed by me.

Apparently there is a configuration bug on Nooknet, and I will forward that to them. I hope they can fix it.

On the other hand, you can use ac-turnip.com.

**Comment by LadyRyu** [comment]
Hello Chris
Good thing I found your page already then. ;-). True, yours (.26) works just fine. Thanks for your work. Greets


Sent from Yahoo Mail for iPhone


On Tuesday, July 21, 2020, 4:00 AM, Christian Ceciliano <notifications@github.com> wrote:




Thank you for reporting this.

Just to let you know. There are two sites that host this tool. Nooknet which is managed by Nooknet and ac-turnip.com which is managed by me.

Apparently there is a configuration bug on Nooknet, and I will forward that to them. I hope they can fix it.

On the other hand, you can use ac-turnip.com.
