### ISSUE TITLE
[FEATURE] Translation error in zh-CN

### ISSUE THREAD

**Issue by LeyingChen** [elxris/Turnip-Calculator#150]
**Is your feature request related to a problem? Please describe.**
There is a translation error in zh-CN version. The original translation that corresponds to "The Most Likely value range is where 50%/75%/90% of the turnip prices will fall" in English is "最可能的区间是指50%/75%/90%的大头菜价格会下降" where '下降' means 'decrease' instead of 'fall'. This might be confusing to Chinese user. 

**Describe the solution you'd like**
Change "最可能的区间是指50%/75%/90%的大头菜价格会下降" to "最可能的区间是指50%/75%/90%的大头菜价格会落在的区间"。

**Comment by elxris** [comment]
I submitted this change to our [translation platform.](https://i18n.ac-turnip.com/projects/turnip-calculator/application/).
If you have more concerns you can open another issue or create an account on the platform and make the change yourself :).
