### ISSUE TITLE
[BUG] Prices above maximum predicted price

### ISSUE THREAD

**Issue by bjhomer** [elxris/Turnip-Calculator#154]
**Version of the tool**
v2.1.2-build.28

**Animal Crossing version**
1.4.2

**Describe the bug**
I'm seeing prices higher than the previous predicted maximum. That reduces confidence in the tool

**To Reproduce**

These were my prices this week.
Purchase price: 92
Monday AM: 72
Monday PM: 76
Tuesday AM: 72
Tuesday PM: 124

At this point, the prediction looks like this:
<img width="940" alt="Screen Shot 2020-08-26 at 10 21 53 AM" src="https://user-images.githubusercontent.com/276263/91329974-0d1f2400-e786-11ea-9c09-ee630697caf7.png">

Then I came to Wednesday AM, and found my price was 181. The previously-predicted _maximum_ for Wednesday AM was 129, which means that the maximum was wrong. Maybe the turnip pricing algorithm changed recently?

_Hopefully_ this means I've got a great price this afternoon… but I'm not sure if I can trust it.

<img width="924" alt="Screen Shot 2020-08-26 at 10 25 44 AM" src="https://user-images.githubusercontent.com/276263/91330730-10ff7600-e787-11ea-9856-0f0396264642.png">

**Expected behavior**
It shouldn't be possible to get prices higher than the predicted maximum.

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - Browser: Safari 
 - Version:  14.0 (beta)

**Comment by bjhomer** [comment]
(Update: Wednesday PM price is 382)

**Comment by elxris** [comment]
Hi @bjhomer 

We use Niji's [datamined code](https://gist.github.com/Treeki/85be14d297c80c8b3c0a76375743325b).

For high spike, we know that on Monday [buy price will be multiplied by a factor of 0.85 to 0.9](https://gist.github.com/nonopolarity/4c0716f7cc6d13b092c5194c2f74edac#file-turnipprices-cpp-L309). If you say that 92 is your buy price, then at minimum your Monday AM price should be 79. Which is more than your recorded 72.

We have some heuristic algorithms so we can detect and fix a pattern that doesn't seem to match anything. So for that reason, we fixed later as more data was recorded.

I hope this was helpful. If you have more issues, please feel free to open another ticket.

**Comment by elxris** [comment]
Your Monday AM price was 82. That way it seem to behave as expected.
