### ISSUE TITLE
[BUG] Crashes if you input specific numbers into "Buy Price"

### ISSUE THREAD

**Issue by sindastra** [elxris/Turnip-Calculator#157]
**Version of the tool**
v2.2.1-build.12

**Describe the bug**
If you enter a specific type of number into the buy price, the tool will permanently crash (due to cookie, it will crash on each visit again).

**To Reproduce**
1. Enter a specific number into "Buy Price", for example 1435634636 or 18987987 or 123456.
2. Hit enter.
3. Wait a bit.

**Expected behavior**
It should not crash.

**Desktop:**
 - OS: macOS 11.1
 - Browser: Firefox
 - Version: 84.0.1

**Screenshot:**
![image](https://user-images.githubusercontent.com/1236984/103479240-9ac1ee80-4dcc-11eb-812c-c3f7579d10d7.png)

**Additional Info**
You can recover from it by deleting all cookies for the site, but not by using the "Clear All Data" button on the site itself (because it's frozen). For an average user, the site would now be permanently broken. At first, I thought it's just because it's a large number, but if I enter a large number like 9999999999 it will be fine. So far, it seems to be relatively large numbers that start with the number one. So, perhaps add a check to not accept large numbers in general.

**Comment by elxris** [comment]
Thank you! I will review this ASAP
