### ISSUE TITLE
[BUG] Spanish version of the site contains english wording

### ISSUE THREAD

**Issue by byronogarcia** [elxris/Turnip-Calculator#173]
**Version of the tool**
v2.2.1-build.26

**Describe the bug**
In the Monday AM spot in the 'Espanol' version should have the word: "Ahora." 
Currently it still has the word, "Now"

**To Reproduce**
1. Go to the main site
2. Click on 'Espanol' on the bottom

**Expected behavior**
A change of the wording from 'Now' to 'Ahora'

**Screenshots**
<img width="147" alt="Screen Shot 2022-02-14 at 2 42 59 AM" src="https://user-images.githubusercontent.com/16056012/153849431-ad380e71-2363-4a78-89f8-1afc6449141b.png">

**Desktop (please complete the following information):**
 - OS: macOS BigSur
 - Browser: Firefox
 - Version: 96.0.2

**Comment by elxris** [comment]
Thanks for you ticket.

The translation platform was down, but now is up again at i18n.ac-turnip.com

In order to see if the platform works again I made the change in: d58d152587526cceba14b51c150769b2dedfd847.

Closing this!
