### ISSUE TITLE
Internationalization is good, but let us choose the language

### ISSUE THREAD

**Issue by JarodDif** [elxris/Turnip-Calculator#29]
Hi, I really like this project and the work put behind this is admirable

I'm pleased to see that the site is translated in different languages, but the core mechanic of changing the language is missing.

My PC is in German, but I would prefer to be able to use this tool in English...

If this is already implemented but I'm too dumb to find it, I'm sorry ;)

**Comment by mtaylor76** [comment]
You're right, currently the site uses your browser's default language and there's no mechanism in the site for changing the language other than that.

I'll make a quick fork to add a dropdown/button/something similar to choose your language, in case the browser's default language doesn't match your preferred language.

**Comment by elxris** [comment]
Can we avoid dropdowns/buttons?

I would like to have a list with languages. As links. At the bottom of the page. This would require each language name string in the translations file.

Something like

English | Español | Français | ... and so on.

Selected language should be remembered from a cookie or local storage.

We shouldn’t use parameters in the url.

**Comment by mtaylor76** [comment]
Absolutely something that can be done, then. I'll make sure it fits those criteria.
