### ISSUE TITLE
[REQUEST] Allow creating share-able links

### ISSUE THREAD

**Issue by sircinnamon** [elxris/Turnip-Calculator#32]
I'm thinking you could encode the numbers into a queryparameter that would load in the linked numbers without overriding your local storage filters.

Maybe you could format the same way, just an array like `[100,81,77,,,,,,,,,,,]` and then just base64 encode so `https://elxris.github.io/Turnip-Calculator/?filters=WzEwMCw4MSw3NywsLCwsLCwsLCwsXQo=` would drop those numbers in.

Do you think this is a good idea? Is `filters` a good name for the queryparam? I'd love to work on this feature if you think it's worth implementing.

**Comment by ysc3839** [comment]
I think it's better using `#hash` instead of `?query`.

**Comment by sircinnamon** [comment]
Yep, could do! As long as there's no other feature that would want to also utilize the hash at the same time (which seems reasonable).

**Comment by bluegill215** [comment]
I have a group of friends, and we all use a common google sheet to track our prices, and we were just talking about wanting this capability. If this existed, we would be able to have a sheet macro that would take us straight to this tool with our weekly turnip prices filled in. I fully encourage your efforts!

**Comment by sircinnamon** [comment]
@bluegill215 The exact same situation made me think of doing this!

I have a working messy v0 of the feature (see https://github.com/sircinnamon/Turnip-Calculator/commit/d07e4a7feec1b39f0f59ffb332065e7ef6d98816), it basically adds a mode switch on the page load, if a hash is present in the url it will not touch the localStorage filters (In theory "your" values) and will show you the values stored in the hash (stored in the format "x/y/z", base64 encoded). If you update the numbers, you the hash will update with your changes, local storage will remain untouched.

There are a few things I'd want to add before merging this: 

1. Handling badly encoded hashes (just remove hash, redirect to original behavior)

2. Add a "Share" button which in some way creates and gives this url to the user (Where?)

3. Figure out what behavior works best with the Clear Data button when viewing in hash mode. Clear hash and reset to viewing the localStorage filters?

Open to suggestions on all of this.

**Comment by elxris** [comment]
Yeah, I think it's against the rules to add hooks inside if blocks.

**Comment by sircinnamon** [comment]
Oh, good to know, I'll adjust. I'm a little new to React still.

**Comment by elxris** [comment]
@sircinnamon I have some free time, do you want me to take over?

**Comment by sircinnamon** [comment]
@elxris I think I have a good fix in mind that I can push up tomorrow, but if you want to get it going sooner than that then go for it

**Comment by elxris** [comment]
I will take a look to see if I can come up with a good solution. Thank you!

**Comment by elxris** [comment]
I think I have come with a good solution!

It's not yet implemented but I have created a hook for state management of shared data.

Shared data is parsed from the hash part of the location.

https://github.com/elxris/Turnip-Calculator/blob/master/src/utils/useShare.js

I will continue tomorrow. It's 2 AM. I love all contributions so far, but 35 pull requests in two days are heavy work!

Basically, what I think it's good enough it's a modal containing a chart that appears each time you open a shared link.

Just next to "clear all data!" button there will be a "share" button.

This share button will open said modal, with a chart. At the same time, it will show you a link you can copy.

When someone uses that link it will immediately open that modal.

So, local changes are not overwritten with link-shared data. And everybody is happy.

Right now my major concern is what if the chart behaves weird inside the modal. But I will test it tomorrow morning.

**Comment by ysc3839** [comment]
@elxris I think we could add a query `?temp=1`. When this query is present, all data will not be saved to localStorage.

**Comment by elxris** [comment]
This would require a button to "recover" your saved data.

**Comment by ysc3839** [comment]
@elxris Just make the title an anchor, so user can click it to "recover" data.

**Comment by sircinnamon** [comment]
@elxris For my own learning, I continued with my implementation on my fork. Organizationally its not ideal 😂 (As well as a little behind with your refactors) but if there's anything there that might be worth incorporating I could try and port it forward on a fresh fork.

I've implemented:

- A flag for being in "import mode" or not
- A share button which pops out a window with a shareable link
- A switch on the Clear Data button when in import mode to clear the import and return to the localstore data (Could be used similar with a temp flag to clear out of temp mode and recover?)

**Comment by elxris** [comment]
How is this loking?

https://ac-turnip.com/feat-share/#102,57,53,49,45,40,,,122

**Comment by sircinnamon** [comment]
I think that fills the need nicely!

**Comment by mtaylor76** [comment]
Implemented in 972ca67. Thanks for the suggestion!
