### ISSUE TITLE
Add tickbox for "first week buying on your island"

### ISSUE THREAD

**Issue by PandorasFox** [elxris/Turnip-Calculator#4]
The first week you buy turnips from your island, the game rerolls your prices on the next Monday morning (including base price) & forces you onto the small spike pattern. This adds some unpredictability as to what the base price is, but at least the pattern is known.

**Comment by elxris** [comment]
Thank you for the suggestion!

I think we should aim for simplicity. A big number of players put "buy price" as "the price they bought". So, I made a change to try to filter with buy price, and then if no results were returned, it will try without the given buy price.

This would be the same case of "first week". The buy price is different than the one used in calculations. But the tool should definitely throw some useful patterns of prices.

Check it out as it is live right now and tell me what you think!

**Comment by PandorasFox** [comment]
Ah, cool, thanks - I've had the same problem with a few different groups (people marking their island buy price as their own buy price), haha.

Looks fine to me, in that case 👀
