### ISSUE TITLE
Lost the local storage data after the domain change

### ISSUE THREAD

**Issue by timwangdev** [elxris/Turnip-Calculator#43]
I've noticed the domain the changed from https://elxris.github.io/Turnip-Calculator/ to https://ac-turnip.com/ that causing old localStorage not accessible.

I suggest can we not force the redirect the website to the new domain until weekend?

**Comment by elxris** [comment]
Sorry about that! You're right!

**Comment by timwangdev** [comment]
@elxris Thanks! But there is another issue with the current GitHub Pages version that the subresources requested the root path `https://elxris.github.io/src.a09119a3.js` instead of `https://elxris.github.io/Turnip-Calculator/src.a09119a3.js`, which returns 404 in the broswer.

**Comment by elxris** [comment]
Thank you! I was having a hard time with the DNS change and the page is not working for me.
The fix is deployed.
