### ISSUE TITLE
Small Error in new language switcher

### ISSUE THREAD

**Issue by JarodDif** [elxris/Turnip-Calculator#44]
Hi again

I issued #29 and I appreciate the work done

Currently the German button is "Deutsche", but "Deutsch" would be correct
I don't know how the language checker is handled, my web-dev knowledge is to low to try correct it myself

I know it's no important change, but still nice to have

**Comment by elxris** [comment]
Thank you! I will do the change!

**Comment by elxris** [comment]
Deployed!
