### ISSUE TITLE
Website doesn't work on Firefox ?

### ISSUE THREAD

**Issue by JarodDif** [elxris/Turnip-Calculator#47]
Hello

On Firefox, I tried 1 hour ago to connect to ac-turnip.com and it didn't work and now it still doesn't.
I opened Chrome and the website works

Can someone check if I'm not the only one where it doesn't work on Firefox, else just close this issue
I just find it weird that it works only on Chrome now, bc this early morning 8:00 UTC+1 it still worked on Firefox

**Comment by Ekaekale** [comment]
Just tried right now, it works for me. 
I installed Firefox just for that so I have the latest build.

**Comment by NiPfi** [comment]
For me it doesn't work on any Browser due to a connection timeout. It seems like the webhost isn't able to handle the traffic and is basically DoSed.

**Comment by Ekaekale** [comment]
> For me it doesn't work on any Browser due to a connection timeout. It seems like the webhost isn't able to handle the traffic and is basically DoSed.
> @Ekaekale What kind of hosting solution do you use? This kind of application might already require some Cloud based hosting solution, since it could become very popular.

Hi, I'm not the creator of this web-app but @elxris could answer you ! :)

**Comment by NiPfi** [comment]
> > For me it doesn't work on any Browser due to a connection timeout. It seems like the webhost isn't able to handle the traffic and is basically DoSed.
> > @Ekaekale What kind of hosting solution do you use? This kind of application might already require some Cloud based hosting solution, since it could become very popular.
> 
> Hi, I'm not the creator of this web-app but @elxris could answer you ! :)

Whoops, sorry my bad. I got you confused.

**Comment by DevSplash** [comment]
Try clearing the browser cache. The link was previously redirected to `ac-turnip.com`, but the domain is unavailable now.

**Comment by NiPfi** [comment]
I see. Problem is, if you clear browser cache it might also delete the entered data. It looks like it uses HTML5 LocalStorage.

**Comment by DevSplash** [comment]
> I see. Problem is, if you clear browser cache it might also delete the entered data. It looks like it uses HTML5 LocalStorage.

1、Press F12 to open Developer Tools. 
2、Go to Network Panel. 
3、Check "Disable cache". 
4、Refresh the page.

**Comment by JarodDif** [comment]
So I tried @DevSplash steps and it didnt work
I ran CCleaner (I'm not making publicity) and it must have cleared my cache and now the website works again
Though it would be nice that this problem doesn't repeat...

**Comment by DevSplash** [comment]
> So I tried @DevSplash steps and it didnt work
> I ran CCleaner (I'm not making publicity) and it must have cleared my cache and now the website works again
> Though it would be nice that this problem doesn't repeat...

Open this [link](https://elxris.github.io/Turnip-Calculator/) instead of [ac-turnip.com](https://ac-turnip.com/).

**Comment by JarodDif** [comment]
I tried both sorry

**Comment by elxris** [comment]
Sorry about that.
The page is hosted at github. That can handle any amount of traffic.
But, I wanted to do a domain change. The new domain would be ac-turnip.com.
I totally forgot about the storage mechanism we use for the data. Some people rely on our storage mechanism for their data. And it’s bounded to the domain.

I reverted the domain change until the weekend.

And as for the problem. Don’t know why browsers are having timeouts. Probably due DNS cache.

**Comment by timwangdev** [comment]
I believe it is the browser caches the link redirection, but the redirection is later removed for a fix and ac-turnip.com is currently not available right now. Since the browser will cache the redirection for a very long time, you have to manually clean it or use dev tools to disable cache.

@elxris I'm sorry that seems the issue #43 has led those problems. A workaround I found in this [Stackoverflow post](https://stackoverflow.com/questions/9130422/how-long-do-browsers-cache-http-301s) suggests that you could host ac-turnip.com on a different site (for example, another GitHub page) and make a javascript redirect back to elxris.github.io/Turnip-Calculator, this will correct the redirection path without extra effect.

**Comment by elxris** [comment]
@timwangdev I have done that. I hope it helps.

**Comment by DevSplash** [comment]
> @timwangdev I have done that. I hope it helps.

Looks like there's something wrong with the site's certificate.

**Comment by elxris** [comment]
It is working now?

**Comment by DevSplash** [comment]
> It is working now?

It worked. XD
