### ISSUE TITLE
Model shows future values that ar not possible for Random/Fluctuating pattern

### ISSUE THREAD

**Issue by adamadam78** [elxris/Turnip-Calculator#51]
Using the input data of:
Buy: 90 
Price: 66,61,54,83,99 through Wed AM

This pattern should be the Random/Fluctuating type of pattern.  Given this data the model on your tool shows possible values that range from 22 to 181.  Given the pattern it should dip down then back up at some point.  Minimum would be 45 and max would be 126.

When the value of 64 is put in for Wed PM it show the correct pattern.  It seems to assume there is the possibility of a small spike until that value is put in.

I'm not the best at code, but let me know if I can help.

**Comment by elxris** [comment]
Related: #14

**Comment by elxris** [comment]
What, tool are you using?
Mike's showing only Fluctuating, but other tools show a high spike as well.
![image](https://user-images.githubusercontent.com/1855014/78954047-7d136300-7aa0-11ea-8d6c-2187cbc28126.png)

I'm detecting random and low spike.
![image](https://user-images.githubusercontent.com/1855014/78954238-16427980-7aa1-11ea-98d7-b9b134945ba5.png)

We're working on new fixes for data model #14, but I think it would not change a lot what patterns are detected.

**Comment by adamadam78** [comment]
I was using Mike's Tool.  I will go back and verify with the documented algorithms.  Thanks.  I will close for now.
