### ISSUE TITLE
Feature Improvement - Datatips Info Timeout

### ISSUE THREAD

**Issue by reocyx** [elxris/Turnip-Calculator#52]
Datatips on mobile block most of the chart. Any way to make those go away? Once they appear, I can't find a way on mobile to remove the datatips pop up. Maybe add a timeout to cause them to drop away after a few seconds or maybe after a second tap on the same point?

Minor QOL change but I'd find it much more readable this way

**Comment by dstaley** [comment]
You can dismiss the tooltip by tapping outside of the graph's green box.

**Comment by elxris** [comment]
Fixed on https://github.com/elxris/Turnip-Calculator/commit/855257678b240506ba0b0cca8bd6022501c73d57
