### ISSUE TITLE
graph won't show if i put in my friday prices

### ISSUE THREAD

**Issue by amazingakita** [elxris/Turnip-Calculator#54]
these are all genuine prices, i had a real bad week for turnip prices:
monday: 47/45
tuesday ??/35
wednesday: 122/87
thursday: 135/168
friday: 77/??

and as soon as i add the 77, the whole colours disappear from the background. 
before:
![image](https://user-images.githubusercontent.com/39305711/78981664-4d07a680-7b18-11ea-80be-b09d86902cee.png)

after:
![image](https://user-images.githubusercontent.com/39305711/78981641-3f522100-7b18-11ea-8b7d-7416f7042d8a.png)

i assume this is by design, however it's strange to see the whole graph go away with genuine prices

**Comment by dstaley** [comment]
I believe this is due to the fact that there's likely an error in your price recording. As far as I can tell, there's no way to have had a sell price of 35 for Tuesday PM and a price of 77 for Friday AM.

**Comment by mtaylor76** [comment]
If the graph colours disappeared and only showed the red line, it means your data is seen as invalid and doesn't match any possible patterns the calculator knows.

Do you think it's possible you accidentally put 77 as your Fri AM price, when it was supposed to be your Fri PM price? With your data, the minimum price you could have for Fri AM is 124.

**Comment by mtaylor76** [comment]
Closing for now, if you have more relevant data please post in #67.
