### ISSUE TITLE
[request] ability to hide max/average/min tooltip

### ISSUE THREAD

**Issue by Therealgano** [elxris/Turnip-Calculator#56]
As the title states, just a small QOL suggestion. I find myself trying to get a look at my full graph for the week but on mobile that tooltip takes up a good chunk of screen space right where I'm trying to look.

Thank you for the calculator! If its projections are accurate I'm looking at a sharp spike to the 400 range in an hour :) pretty stoked

**Comment by dstaley** [comment]
If you tap outside of the graph's green box, it will dismiss the tooltip.

**Comment by Therealgano** [comment]
Oh man I guess I didn't fiddle hard enough, thanks!

**Comment by markadilus** [comment]
No problem. Great tool and all. Like for real good job. Just it only worked
about 50% of the time for me.
