### ISSUE TITLE
Empty chart? Post here

### ISSUE THREAD

**Issue by elxris** [elxris/Turnip-Calculator#67]
Please post here your input data if the calculator can't give you a result.

Example format:
```
Version: 1.9.0
Buy price: 90
Mon ??, 90
Tue 80. ??
Wed ??, 90
...
```

It is not necessary to fill days you don't know the date.

**Comment by amazingakita** [comment]
monday: 47/45
tuesday ??/35
wednesday: 122/87
thursday: 135/168
friday: 77/72

(re: the question you asked, no, it wasn't possible as i was posting the question at friday am for me)

**Comment by benhid** [comment]
```
Buy price: 99
Mon 156, 68
```

**Comment by dcmeier** [comment]
Buy Price: 97
Mon: 133/108
Tue: 121/81
Wed: 113/141
Thur: 72/100
Fri: 59/132
Sat ??/??

Buy Price: 91
Mon: 82/78
Tue: 75/71
Wed: 67/63
Thur: 60/109
Fri: 247/386
Sat 141/??

**Comment by jacobspeicher** [comment]
Buy price: 91
Mon: 72 / 75
Tues: 112 / 155
Wed: 233 / 144
Thurs: 111 / ??
Fri: ?? / ??
Sat: ?? / ??

**Comment by Pompadore** [comment]
Buy price : 105

Mon : 45/46
Tues : 122/129
Wed : 49/41
Thurs : ??/97

**Comment by Mapl3h3art** [comment]
Buy price: X
Mon ??, ??
Tue 81. ??
Wed 205, ??
Thu 475, 185

**Comment by braxtongill** [comment]
```
Buy price: 99
Mon: ??, ??
Tue: ??, ??
Wed: ??, ??
Thu: ??, 613
Fri: 73, ??
Sat: ??, ??
```

**Comment by prplchkn08** [comment]
Wed PM 170
Thur: 140/172
Fri 159/61
Sat 56

If I remove Saturday and Friday the graph comes back

**Comment by elxris** [comment]
I pushed a new heuristic filter! (v1.9.0)
It is meant to filter out any precision errors on our side but is also capable of filtering out your input errors. It's activated only when previous filters didn't throw any result. So while it's guessing your best pattern it could have some hiccups. Keep inputting the next days, more data, more precise it is your result.
