### ISSUE TITLE
the link is Redirecting 

### ISSUE THREAD

**Issue by icedrowning** [elxris/Turnip-Calculator#68]
[You can find the live calculator here.]
which I click the word here and  I couldn‘t  get the Calculator，web page shows that page is Redirecting ...

**Comment by elxris** [comment]
Thank you! Please use a hard reload of the page.

The new site is ac-turnip.com

**Comment by darknerd42** [comment]
@elxris ac-turnip.com has a Cert error for me (NET::ERR_CERT_INVALID): Looks like the certificate expired on April 16th.

**Comment by alexpersian** [comment]
Site is currently in a redirect-loop on mobile. On desktop it warns about an invalid cert. 

![image](https://user-images.githubusercontent.com/5446451/79125695-905a5300-7d6c-11ea-93b6-93d6ad3e97bb.jpeg)

![image](https://user-images.githubusercontent.com/5446451/79125707-93edda00-7d6c-11ea-959c-2b86f53805c5.png)

**Comment by elxris** [comment]
@darknerd42 @alexpersian Can you take a screenshot of the cert?
I'm seeing this:
![image](https://user-images.githubusercontent.com/1855014/79127610-d365f780-7d67-11ea-9ae5-071e7a8a67e5.png)

@darknerd42 if expired on April 16th, and today is the 13th, it is not expired, right?

**Comment by darknerd42** [comment]
@elxris My bad - I misread the error. The root certificate is not trusted for me. 
![image](https://user-images.githubusercontent.com/6234079/79130611-3e69fb00-7d75-11ea-9b10-4ef88cab0520.png)

**Comment by darknerd42** [comment]
Oddly, it is working for me on mobile - Maybe a DNS cache somewhere is still stale? Hopefully that means it will all get sorted out on it's own.

**Comment by elxris** [comment]
Yes, probably that, I hope this resolves in the next 12-24 hours. I hope browsers did not cache this more than that.

**Comment by StarlightLumi** [comment]
Website is currently returning a 404.

![96C62B4A-B864-49B9-9848-F23C8B70AFBF](https://user-images.githubusercontent.com/27462521/79132689-6440d100-7d70-11ea-8715-1dd8ff4796e3.jpeg)

**Comment by elxris** [comment]
😓 , thank you!

I didn't notice how important is the CNAME file in the gh-pages branch.

This will not happen again, I made a necessary step to make myself sure.

**Comment by alexpersian** [comment]
@elxris I've dealt with this challenge using GitHub Pages before as well. It's frustrating! Thank you for continuing to support this service though 🙏

**Comment by elxris** [comment]
I will close this issue due to no more incidents.
