### ISSUE TITLE
[Minor, Aesthetic] Share link contains default react-app messaging

### ISSUE THREAD

**Issue by itscandis** [elxris/Turnip-Calculator#70]
Sharing via the `Share!` link results in only default react messaging:
https://elxris.github.io/Turnip-Calculator/#109,147
![Screenshot_26](https://user-images.githubusercontent.com/34015360/79129832-e383d400-7d73-11ea-893a-35ff498aa979.jpg)
This should be updated so it reflects the actual site data if possible.

**Comment by ysc3839** [comment]
#71 This pr may fix that issue.

**Comment by itscandis** [comment]
Awesome! I should have checked the PRs. 👍

**Comment by elxris** [comment]
It was created after your post! Thank you both for reporting and fixing!
