### ISSUE TITLE
Average price is below the guaranteed minimum

### ISSUE THREAD

**Issue by timothyrichards** [elxris/Turnip-Calculator#73]
I don't think this is supposed to be able to happen but I'm not sure, I thought I should report it regardless.

![image](https://user-images.githubusercontent.com/59814951/79139563-62284380-7d6b-11ea-91fe-77f832343867.png)

**Comment by Elsensee** [comment]
The guaranteed minimum must be seen as a weekly value. During the week you will *at least* see this price. That doesn't mean that on some days the price can't be lower. It just means, that this is the minimum price you can sell your turnips for.

**Comment by elxris** [comment]
Thank you @Elsensee, that’s exactly what it means. @timothyrichards I will close this. But feel free to open another issue if you see something wrong.
