### ISSUE TITLE
Result graph decreases slowly in height on page load

### ISSUE THREAD

**Issue by andreasjhagen** [elxris/Turnip-Calculator#74]
When load the site, I can see the result graph below BUT it is decreasing in height over time which prevents me from being able to see the result after a specific time has passed.

Gotta admit tho, looks kinda hilarious. I attached a preview of it. 

Using Edge Chromium 80 on Windows10
![Bug](https://user-images.githubusercontent.com/20399130/79158924-77d35280-7dd7-11ea-961d-54ad66efd7c0.gif)

**Comment by elxris** [comment]
lol, thanks for the video!
But closing as duplicated #64
