### ISSUE TITLE
Catalan translation

### ISSUE THREAD

**Issue by UABaena** [elxris/Turnip-Calculator#75]
Hi guys, first of all good job, i did the catalan translation (code ca) how can i add it to the master?

i cloned the repo and i transalated and commited, but when i tried to upload i got a 403 error because i'm not a collaborator

what i need to do for upload the translation?

Cheers

**Comment by elxris** [comment]
Thank you a lot. If you were using i18n.ac-turnip.com you are good, you don't need to do anyting else.
