### ISSUE TITLE
Previous week's data?

### ISSUE THREAD

**Issue by TheJadeKitten** [elxris/Turnip-Calculator#77]
I'm just curious, when the week rolls over do I clear data and start over? Or do I leave last week's data in the fields?

**Comment by mtaylor76** [comment]
You should clear last day's data whenever a new week begins. Does that
answer your question?

**Comment by TheJadeKitten** [comment]
Yes, perfectly, thank you!

**Comment by mtaylor76** [comment]
Closing as answered.
