### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Ekaekale** [elxris/Turnip-Calculator#8]
Hi, I would love to help you with this application. I would like to translate it in French to share to my friends but I don't really know how to ... xD 
Maybe you can tell me how to :)

**Comment by elxris** [comment]
I would love to, but currently, it doesn't have support for internationalization. I hardcoded all string.
Please allow me, or someone in the community to add support for i18n.
I will mark this as "Good first issue"

**Comment by elxris** [comment]
We can start to localize to french.
We need to update this file: https://github.com/elxris/Turnip-Calculator/blob/master/locales/fr/translation.json
