### ISSUE TITLE
Guaranteed Minimum changed mid-week

### ISSUE THREAD

**Issue by NightmareCorporation** [elxris/Turnip-Calculator#81]
My island has a decreasing trend - the calculator had a guaranteed minimum of 134 until today, where it correctly detected the downward trend and adapted the guaranteed minimum.

I am not sure if this is desired behaviour for a "guarantee", here is the data for the week:
Buy: 97
78 - 80 - 77 - 74 - 70 - 66 - 62 -59

Until entering the 59 for Thu PM the guaranteed minimum stays at 134.

If it is intended behaviour please change the wording to "expected minimum" or "probable minimum"

**Comment by elxris** [comment]
Thank you!

I updated the tool to 1.9 and a new feature I like to call "heuristic filter" will help to point errors.
![image](https://user-images.githubusercontent.com/1855014/79709213-3800e500-8287-11ea-94cf-0a7c37df5e4d.png)

I am not finding culprits but, or we don't have the complete algorithm that determines the prices, or at the time of recording data, we did a mistake. If you watch closely you will see that the new graph shows that the first value is not likely.

This "heuristic filter" will occur when "normal filter" fails. Guaranteed minimum should work if "normal filter" happens to work. If not, it will show the guaranteed minimum of "heuristic filter".
