### ISSUE TITLE
Chart Pattern Doesn't Exist?

### ISSUE THREAD

**Issue by theblackspeed** [elxris/Turnip-Calculator#83]
I had a price fluctuation happen that apparently doesn't exist and just hoping I can get some insight on that as to why it happened?

I attached a screenshot below to hopefully assist.

![Turnip Wrong](https://user-images.githubusercontent.com/27295766/79604890-890caf80-80b4-11ea-8c74-ce1d364dc1a4.JPG)

**Comment by Pompadore** [comment]
Me too!

**Comment by ZacharyPariah** [comment]
I also have the same problem. Here's my chart, even though I missed one entry, if you put a placeholder number in, it doesn't fix it. The one that broke the chart seems to be Friday night, the price was 52. https://ac-turnip.com/#110,54,59,50,86,113,85,,64,57,52,90,128

**Comment by aru** [comment]
What happened on Sat?

**Comment by theblackspeed** [comment]
> What happened on Sat?

I, unfortunately, didn't care once the graph broke. No idea. If I REMEMBER, it tanked more to like 50 a turnip or something.

**Comment by elxris** [comment]
I will close this as is duplicated: #67 

BUT: I have solved the majority of problems with 1.9 release, it includes a new heuristic filter in case all of the previous predictions fail.
