### ISSUE TITLE
Sell price went under the minimum guaranteed

### ISSUE THREAD

**Issue by LaHugue** [elxris/Turnip-Calculator#85]
Hi ! I bought my turnips 103 bells on 04/19, and time-traveled my way through the week,  to test the simulation, first 04/20 10am then 2pm next 04/21 10am then 2pm and on and on.
On Tuesday AM, the price went to 84 for a guaranted minimum of 87, and then kept on falling to a ridicule 47 bells on saturday PM.
I had a promising friday PM but unfortunately it crashed down.

<img width="931" alt="Screenshot 2020-04-19 at 13 34 26" src="https://user-images.githubusercontent.com/63957103/79686996-9062c300-8244-11ea-8a26-68b031647633.png">
<img width="927" alt="Screenshot 2020-04-19 at 13 31 46" src="https://user-images.githubusercontent.com/63957103/79687000-9b1d5800-8244-11ea-890c-2ba942c152df.png">
<img width="928" alt="Screenshot 2020-04-19 at 13 28 07" src="https://user-images.githubusercontent.com/63957103/79686983-82ad3d80-8244-11ea-807d-fd60548d73b4.png">

What did I do wrong ?
Anyway thanks for all the work you put on on this tool !
Greetings from France (excuse the bad english)

**Comment by hkbenchan** [comment]
Is this your first week on buying the turnips (where buying from other players' islands do not count)? If so, the first week sell pricing will not base on what your buying price and thus the tools may not accurate.

**Comment by elxris** [comment]
The guaranteed price was reached on Monday.
The tool guarantee that at least one day the price will be equal or more than the guaranteed price.
That's how it works.
