### ISSUE TITLE
Dirty Cache

### ISSUE THREAD

**Issue by RinCat** [elxris/Turnip-Calculator#89]
Not sure if this is dirty cache or bug in image generator.
https://ac-turnip.com/#90-80-102
https://ac-turnip.com/p-90-80-102.png
The dynamically generated graph is different with the image.

**Comment by elxris** [comment]
Latest version of the calculator is 1.9.x

Check at the bottom of the page if they match.

**Comment by RinCat** [comment]
Now they looked same. Thanks.
