### ISSUE TITLE
Incorrect bump model math

### ISSUE THREAD

**Issue by nanoNago** [elxris/Turnip-Calculator#9]
This is very sleek! I think there's a bug: Try setting prices to 90,87,84,81,78,75,72 to try to narrow this down to a weak bump model; the peak prices are AFAIUI not [153, 221] inclusive but should be:

1.4 * 110 --> 154; and
2.0 * 110 --> 220.

The days before and after the peak should be shifted down by one; so [153, 219].

...If I am understanding ninji's code analysis correctly, anyway.

(I wrote my own price predictor in python; it does not have a very pretty web UI, but I think I have a good idea of what it takes to do backwards analysis for the prices to weed out invalid models.)

**Comment by elxris** [comment]
I'm sorry to ask this, but, if you can it would be pretty awesome.

Currently, all calculations are in https://github.com/elxris/Turnip-Calculator/blob/master/src/v2/optimizer.js

The function named possiblePatterns is the start point.

Could you take a look?

**Comment by jnsnow** [comment]
I'm not a javascript dev so the syntax is a bit ? to me in places.... this will take me a long minute. possible patterns enumerates the models without any price data, correct?

What's the purpose of this map?

.map((v, i) => (i ? v + 1 : v - 1))

**Comment by elxris** [comment]
This line is for mapping a [min, max] array. It substracts one to the min value and adds one to the max value.

This is because sometimes the float operations that javascript does, in 64-bit, don't match quite right the original algorithm in 32-bit. So instead of leaving out some people with in-edge cases where float point operations aren't accurate, I want to include them. This doesn't mean that every min-max pattern is off by one unit. Some cases that's true, some others are not.

**Comment by nanoNago** [comment]
Sorry, I don't follow what rounding math you're trying to achieve. In my example above, let's assume the buy price is 110 and we're on a bump week with the data as mentioned (90, 87, 84, ...)

when we reach the third price of the bump pattern, we're going to roll a price between 1.4 and 2.0 of our base price; so:
1.4 * 110 --> 154.0
2.0 * 110 --> 220.0

then, we take the int ceiling of these values, so our range is now still [154, 220]
but we also subtract one to ensure that the peak value is *always* higher than our own, i.e. [153, 219] is the final actual range for prices 3 and 5 of the bump pattern.

You are computing these values:
1: [98, 155] -- should be [99, 154]
2: [98, 155] -- should be [99, 154]
3: [152, 220] -- should be [153, 219]
4: [153, 221] -- should be [154, 220]
5: [152, 220] -- should be [153, 219]

You have a rather consistent -1 to the minimum and a +1 to the maximum across the board.

**Comment by elxris** [comment]
Thank you for your analysis. What happens with this data?

96 buy price, 86, 81
Or 90 buy price, 82, 78

I was trying to fix for this kind of edge cases.

**Comment by elxris** [comment]
Closing due to no response. And also some changes that happened at #14
