### ISSUE TITLE
Garanteed Minimum is Wrong for me

### ISSUE THREAD

**Issue by EternalStay** [elxris/Turnip-Calculator#91]
Hello ! (I'm french, so sorry if my English is bad :P)

The Garanteed Minimum value is 76 this week for me, but I had 75 yesterday and 72 this morning. What's wrong ?

Thanks for your tool :)

![Screenshot_20200421-081045_Chrome](https://user-images.githubusercontent.com/20124053/79831602-ffa4f800-83a7-11ea-9059-11f08c8c1e64.jpg)
![Screenshot_20200421-081133_Chrome](https://user-images.githubusercontent.com/20124053/79831603-00d62500-83a8-11ea-9cfc-ac670a29c0a2.jpg)

**Comment by rlevet** [comment]
**-- I'm answering in French. --**

"- La valeur Minimum garanti signifie que vous verrez au moins ce prix à un moment donné de la semaine."
Donc, ici, rien qui ne va pas
Ca m'étonne que ton minimum garanti soit aussi bas, d'ailleurs
En gros, ça veut dire que a un moment de la semaine, tu pourras le revendre au moins à 76 clochettes
Souvent il est + élevé que ton prix d'achat. Il ne faut PAS vendre en dessous de ce prix
Ex: Le minimum garanti est de 140, tu as acheté a 95, et aujourd'hui, on te propose 120 le navet
Tu ne dois pas vendre, car a un moment dans la semaine, le prix montera encore + haut (140 clochettes ou +)

Si j'ai bien compris, c'est ça

**Comment by EternalStay** [comment]
Ohhh Thanks ! I didn't understand it like that. My shop is closed tomorrow, great xD
