### ISSUE TITLE
Generated link doesn't populate chart

### ISSUE THREAD

**Issue by capoferro** [elxris/Turnip-Calculator#92]
https://ac-turnip.com/#109,96,145,148

sends me here:

![image](https://user-images.githubusercontent.com/57349/79880684-561d3100-83be-11ea-943f-ba6cda288f06.png)

**Comment by capoferro** [comment]
It looks like the share link functionality got a backwards incompatible change, now that I'm looking at it. Recreating the chart works fine.

https://ac-turnip.com/share?f=109-96-145-148

**Comment by elxris** [comment]
Oh, let me fix it.

**Comment by elxris** [comment]
Fixed!
