### ISSUE TITLE
Different charts between Turnip Prophet and AC Turnip

### ISSUE THREAD

**Issue by capoferro** [elxris/Turnip-Calculator#95]
AC Turnip might be the one with the bug:

![image](https://user-images.githubusercontent.com/57349/79990719-60533400-847f-11ea-9174-561c75208fb8.png)

![image](https://user-images.githubusercontent.com/57349/79990741-677a4200-847f-11ea-9977-4eb4e1658651.png)

https://ac-turnip.com/share?f=109-96-145-148-160-175

**Comment by elxris** [comment]
Let’s keep recording prices, please?

It would help me a lot!

**Comment by tady159** [comment]
I believe that some change may have introduced a bug between version 1.8-beta.a and 1.9.0b.
I was watching a youtube video that showcased version 1.8-beta.a, and it showed the following graph:
![image](https://user-images.githubusercontent.com/8518463/80107183-25b9cc00-8551-11ea-88ac-0362394885c6.png)

Inputting the same data on the current version gives a different graph, showing oddly high values towards the end of the week, with a totally different average curve:
![image](https://user-images.githubusercontent.com/8518463/80107294-47b34e80-8551-11ea-92ca-80a32139f56e.png)

**Comment by capoferro** [comment]
It seems to be inaccurately estimating high potential at the end of the week... the same symptom is on my graph as well. Here's data up to today, btw:

https://ac-turnip.com/share?f=109-96-145-148-160-175-153-68
https://turnipprophet.io?prices=109.96.145.148.160.175.153.68.....&pattern=2

**Comment by BrendanBuono** [comment]
This might be because turnip prophet takes into account your pattern from the previous week, where AC Turnip does not. @elxris , is there a plan to factor in the previous week's pattern? It affects the `whatPattern` chances

**Comment by BrendanBuono** [comment]
Quick follow up regarding previous pattern intake. [This code](https://github.com/elxris/Turnip-Calculator/blob/617aa70e6d984d878978c02cee12c05eea3a6e66/src/utils/patterns.js#L342) sets up probabilities based on what seems like the addition of all four possibilities across the price calculator [here](https://gist.github.com/Treeki/85be14d297c80c8b3c0a76375743325b#file-turnipprices-cpp-L135).

Determining which probability to use would be relatively simple, we can extract the array into a method that chooses based on the previous week, which the user can input. The bigger question is how this is added to the filter, as we would want a backwards compatible change.

My recommendation is to add a second parameter `previousPattern`, which ranges from 0 to 3, and picks the probability based off that. If `previousPattern` isn't present, then the algorithm falls back to the current implementation. @elxris, @capoferro  thoughts?

**Comment by elxris** [comment]
If you watch closely, if you set any previous pattern the graph part of turnipprophet will not change. Previous pattern will only give some finer details of probability.

**Comment by BrendanBuono** [comment]
Totally fair, I didn't actually look at the output from changing the previous week's pattern, my bad!

**Comment by elxris** [comment]
Finally found the root of this bug. Deployed to v2.0.1-build.18

Thanks!
