### ISSUE TITLE
[Request] Allow for store closed day?

### ISSUE THREAD

**Issue by TheLunarAegis** [elxris/Turnip-Calculator#96]
When Nook's Cranny upgrades you can't sell turnips.  It doesn't mess with the trend, but I wish there was a way to lock the value as 'null' or '-'.

**Comment by Eond** [comment]
That does only happen once in any island's lifetime. If it really doesn't affect the trend, then you could just place the prices with a one day offset, putting nothing on Saturday.

**Comment by elxris** [comment]
Doesn’t affect the trend and you could just skip that day.

I will close this as I don’t see a feasible fix.
