### ISSUE TITLE
Wrong Max

### ISSUE THREAD

**Issue by gunnarsundberg** [elxris/Turnip-Calculator#97]
So far, 2 days this week prices have exceeded the max (it's wednesday as I'm typing this). This was before the latest patch and nothing out of the ordinary happened this week (no shop closings etc). Please, let me know if you need more details. Thanks!
Screenshots:
<img width="1312" alt="Screen Shot 2020-04-22 at 8 32 33 PM" src="https://user-images.githubusercontent.com/16456177/80046452-a7b9de80-84d8-11ea-942d-a35c57b58a04.png">
<img width="1312" alt="Screen Shot 2020-04-22 at 8 32 52 PM" src="https://user-images.githubusercontent.com/16456177/80046467-adafbf80-84d8-11ea-982b-ed129bf1acd9.png">
<img width="1312" alt="Screen Shot 2020-04-22 at 8 33 04 PM" src="https://user-images.githubusercontent.com/16456177/80046472-b0aab000-84d8-11ea-8d67-c640c7570eb8.png">

**Comment by elxris** [comment]
I pushed 1.9.1 and is now live.
It still makes a few adjustments but I think is far better, is it some value you entered is not the real value?

![image](https://user-images.githubusercontent.com/1855014/80297263-32077a00-8747-11ea-881a-de723487908a.png)

![image](https://user-images.githubusercontent.com/1855014/80297268-3d5aa580-8747-11ea-8dac-efd24ce338e0.png)

![image](https://user-images.githubusercontent.com/1855014/80297274-45b2e080-8747-11ea-8a75-c96f704ff445.png)

**Comment by gunnarsundberg** [comment]
It was the real value of the turnips that I bought

**Comment by elxris** [comment]
I mean, there is a chance you miss to log your prices accurately? It happens to the best of us.
I will close this because I think there is no much more I can do, but please come back if you see something like this again!.
