### ISSUE TITLE
Market changes post-update

### ISSUE THREAD

**Issue by sdlouhy** [elxris/Turnip-Calculator#99]
Before the update and remodel of Nook's, my market trend was showing an absolute max of 222bells/turnip.  When I checked my market tonight, I had a spike of 432 bells.  I don't know whether the shop closing it update caused this because they happened in the same day

**Comment by elxris** [comment]
Do you have your week data?

**Comment by sdlouhy** [comment]
Yeah, here it is listed below:
MON:
 am - 71 bells
pm - 94 bells

TUES:
am - 88 bells
pm 84 bells

WED: closed for renovation + day before the update

THURS:
am - 194
pm - 436

On Monday/Tuesday, I was getting an entirely different trend line, and my curve fit exactly with the predicted data to that point.  When I checked this morning, I had a completely different trend line that I associated with not having data for Wednesday.  The spike I had this afternoon did not match with the predicted trend from this morning either, so that leads me to believe that the devs may have fiddled with that algorithm in the update.

**Comment by sdlouhy** [comment]
As an addendum, I checked with turnip prophet, and it also is not able to predict what's going on with my island's stalk market, so it's either something new that was added in the update or something that was somehow overlooked while datamining

**Comment by elxris** [comment]
I released 1.9.1 includes some changes to the graph. And I was checking this last version with your data and found nothing out of normal.

This until Tuesday PM:
![image](https://user-images.githubusercontent.com/1855014/80296270-0aacaf00-873f-11ea-8aa9-9bc804b7039a.png)

Then Thursday:
![image](https://user-images.githubusercontent.com/1855014/80296284-2b750480-873f-11ea-8076-c6da69c0eade.png)

**Comment by sdlouhy** [comment]
Yeah, those two seemed to assign with trends.  The one thing that confused me was when I checked Thursday morning, when the graph was showing a peak then, a large dip in the afternoon, and a second, smaller spike Friday morning.  The odd behavior specifically showed up Thursday morning

**Comment by elxris** [comment]
This one is on Thursday morning.
![image](https://user-images.githubusercontent.com/1855014/80297037-51050c80-8745-11ea-97f8-0d65e990dcf6.png)

I think I know what do you mean. The tool shows possibles scenarios. With this update, darker values mean a higher probability.
